### ISSUE TITLE
Twilio errors: HTTP Connection Failure - Read timed out

### ISSUE THREAD

**Issue by alanb2718** [bmlt-enabled/yap#575] opened 2021-12-06 20:40 UTC
We've been seeing HTTP connection failure errors from Twilio -- 5 of them since Dec 1.  This is for the Seattle Area helpline, which uses the WSZF server running yap 4.0.1. 

Here's the most recent error:
`2021-12-05 19:16:49 UTC.     HTTP Connection Failure - Read timed out`

Here are the call details for this (I removed the incoming number, since it would be inappropriate to post this on a public website).

```
Call Details

Give Call Quality Feedback
Details
Insights Summary
Properties

Call SID
CAd10fc0e65f582788254ba1f8401b5c66
Date
11:16:07 PST 2021-12-05
Start Time
11:16:08 PST 2021-12-05
End Time
11:16:53 PST 2021-12-05
Duration
45 sec
Cost
$0.0085
From
+[deleted]
To

+12067908888
Direction
Incoming
Type
Phone
Status
Completed
Stir/Shaken Status 
A
Errors and Warnings

Debug Event SID
NOd4398faca53b715261b8da1bc80ff1ff
Error
11205
Message
HTTP Connection Failure - Read timed out
Request Inspector

+ Expand All
GET
https://bmlt.wszf.org/yap/index.php
2021-12-05 19:16:08 UTC1429ms200
Request
Response
Headers
BodyShow Raw
<?xml version="1.0" encoding="UTF-8"?>
<Response>
    <Gather language="en-US" input="dtmf" numDigits="1" timeout="10" speechTimeout="auto" action="input-method.php" method="GET">
        <Pause length="2"></Pause>
        <Say voice="alice" language="en-US">
                    Seattle Area Narcotics Anonymous                </Say>
        <Say voice="alice" language="en-US" >
                        press one to find someone to talk to                    </Say>
        <Say voice="alice" language="en-US">
                        press two to search for meetings                    </Say>
        <Say voice="alice" language="en-US">
                        press three to listen to the just for today                    </Say>
    </Gather>
</Response>
GET
https://bmlt.wszf.org/yap/input-method.php
2021-12-05 19:16:25 UTC203ms200
GET
https://bmlt.wszf.org/yap/input-method-result.php
2021-12-05 19:16:49 UTC15017ms-1
POST
https://bmlt.wszf.org/yap/status.php
2021-12-05 19:16:53 UTC435ms200


```

**Comment by klgrimley** [comment] 2021-12-06 22:42
In reviewing our twilio error logs. Starting on 11/21 we've had 1 - 7 `Call Progress: Warning Response to Callback URL` warnings per day. On 12/02 we had one `HTTP retrieval failure` error On 12/05 on `HTTP connection failure` error and the same as a warning And on 12/06 one `HTTP connection failure` error Additional log info follows. One per error or warning

### Warning - 15003 Call Progress: Warning Response to Callback URL
**MESSAGE**
`Got HTTP 404 response to https://centralindianana.org/yap/endpoints/status.php`

**Request URL**
`https://centralindianana.org/yap/endpoints/status.php`

**Request Parameters**
`Called | "+13178755459"
-- | --
ToState | "IN"
CallerCountry | "US"
Direction | "inbound"
Timestamp | "Sat, 04 Dec 2021 02:31:55 +0000"
CallbackSource | "call-progress-events"
CallerState | "IN"
ToZip | "46032"
SequenceNumber | "0"
To | "+13178755459"
CallSid | "CA3c59170b64a4751f3ec4eb94fd3e7e07"
ToCountry | "US"
CallerZip | "46220"
CalledZip | "46032"
ApiVersion | "2010-04-01"
CallStatus | "completed"
CalledCity | "INDIANAPOLIS"
Duration | "1"
From | "+13177465094"
CallDuration | "13"
AccountSid | "AC59a0c75be25ea9a0cf7fa6e944ea5c54"
CalledCountry | "US"
CallerCity | "INDIANAPOLIS"
ToCity | "INDIANAPOLIS"
FromCountry | "US"
Caller | "+13177465094"
FromCity | "INDIANAPOLIS"
CalledState | "IN"
FromZip | "46220"
FromState | "IN"`

**Request Message Text**
`Msg | "Got HTTP 404 response to https://centralindianana.org/yap/endpoints/status.php"
-- | --
statusCallback | "https://centralindianana.org/yap/endpoints/status.php"
ErrorCode | "15003"
LogLevel | "WARNING"`

**Response Headers**
`Transfer-Encoding chunked
Server nginx
X-Proxy-Cache-Info DT:1
X-Twilio-WebhookRetriable false
Pragma no-cache
Date Sat, 27 Nov 2021 03:20:52 GMT
Host-Header 8441280b0c35cbc1147f8ba998a563a7
Cache-Control no-cache, private
X-Twilio-WebhookAttempt 1
Set-Cookie XSRF-TOKEN=eyJpdiI6Im02T0lhUm1neU1uZE1tZUc1SHFoMkE9PSIsInZhbHVlIjoiSWFacW8xRWRSeFJCWkNZajJLNXNyUUV2YVZ2ZnpFTithRzJXdkpQWlNqT3pQWGF0WFFEYVU2bVlDM2k3WW41ZWtxbnh4b21NYy9JSUg4SDBpc29zOU9GWi9QY0ZKeFl4M1FQcFI2TkJWRmRYWlpKMktwUFQxZTlSVUl2eVFPdk0iLCJtYWMiOiIxYmQ5ZjlhMmM1YWJlNjY5MjBmNzIzYWJlNjYxNDM1NDk4OTY3MzY2ZTMwNTVhNDBiMDU4ZWZlOGVlMzg3MTU3IiwidGFnIjoiIn0%3D; expires=Sat, 27-Nov-2021 05:20:52 GMT; Max-Age=7200; path=/; samesite=lax
Vary Accept-Encoding
Expires -1
X-Httpd 1
Content-Type text/html; charset=UTF-8`

Response Body
`404`

### Error - 11200 HTTP retrieval failure
**Message**
`An attempt to retrieve content from https://centralindianana.org/yap/helpline-answer-response.php?conference_name=1_4351017_1638458408&service_body_id=1&ysk=a56edc4dc4db1a30acdb0783a01955ca returned the HTTP status code 500`

**Request URL**
`https://centralindianana.org/yap/helpline-answer-response.php`

**Request Parameters**
`msg | "Gather End"
-- | --
Called | "+13177435256"
Digits | ""
ToState | "IN"
CallerCountry | "US"
Direction | "outbound-api"
CallerState | "IN"
ToZip | ""
CallSid | "CA9ac24e5464bed68a8bd0a61a27b7646d"
To | "+13177435256"
CallerZip | "46032"
FinishedOnKey | ""
ToCountry | "US"
ApiVersion | "2010-04-01"
CalledZip | ""
CallStatus | "in-progress"
CalledCity | ""
From | "+13178755459"
AccountSid | "AC59a0c75be25ea9a0cf7fa6e944ea5c54"
CalledCountry | "US"
CallerCity | "INDIANAPOLIS"
Caller | "+13178755459"
FromCountry | "US"
ToCity | ""
FromCity | "INDIANAPOLIS"
CalledState | "IN"
FromZip | "46032"
FromState | "IN"`

**Request Message Text**
`msg | "An attempt to retrieve content from https://centralindianana.org/yap/helpline-answer-response.php?conference_name=1_4351017_1638458408&service_body_id=1&ysk=a56edc4dc4db1a30acdb0783a01955ca returned the HTTP status code 500"
-- | --
Msg | "An attempt to retrieve content from https://centralindianana.org/yap/helpline-answer-response.php?conference_name=1_4351017_1638458408&service_body_id=1&ysk=a56edc4dc4db1a30acdb0783a01955ca returned the HTTP status code 500"
sourceComponent | "13300"
ErrorCode | "11200"
httpResponse | "500"
url | "https://centralindianana.org/yap/helpline-answer-response.php?conference_name=1_4351017_1638458408&service_body_id=1&ysk=a56edc4dc4db1a30acdb0783a01955ca"
LogLevel | "ERROR"`

**Response Headers**
`Transfer-Encoding chunked
Server nginx
X-Proxy-Cache-Info 0 NC:000000 UP:SKIP_CACHE_SET_COOKIE
X-Twilio-WebhookRetriable false
Pragma no-cache, no-cache
X-Proxy-Cache MISS
Date Thu, 02 Dec 2021 15:21:14 GMT
Host-Header 6b7412fb82ca5edfd0917e3957f05d89
Cache-Control no-store, no-cache, must-revalidate, no-cache, private
X-Twilio-WebhookAttempt 1
Set-Cookie laravel_session=eyJpdiI6IklXQ2JIR29HeWV4OUsxWWRyL1pPNFE9PSIsInZhbHVlIjoiQjU3UW11NHM2K0srR3dSaTVBTkZpYzY2cFZKSElwaE5aVFdubWw1TkhGbVFHRWdySmlzWWptQVBFeWFKUzBUSGFUZmg1QVZ6bUZ3b3Iya3Evb1I0MG5LOHlEZkQ3Q24xcWRROXJvaDkrL1o0OGRJSXVBWEdweGZ0OFlldS9PcFkiLCJtYWMiOiIzMGJkMmFlMDQwNGI4ZWI4MmU0ZjZkN2FmMzA2NWFlY2EwODczOWZkMzdhNGM4ZmFmYjUwNTVhN2Y2NTM2MDFmIiwidGFnIjoiIn0%3D; expires=Thu, 02-Dec-2021 17:21:14 GMT; Max-Age=7200; path=/; httponly; samesite=lax
Expires Thu, 19 Nov 1981 08:52:00 GMT, -1
X-Httpd 1
Content-Type text/html; charset=UTF-8`

**Response Body**
`<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1">
                <title>Server Error</title>
                
                <link rel="preconnect" href="https://fonts.gstatic.com">
                    <link href="https://fonts.googleapis.com/css2?family=Nunito&display=swap" rel="stylesheet">
                        <style>
            /*! normalize.css v8.0.1 | MIT License | github.com/necolas/normalize.css */html{line-height:1.15;-webkit-text-size-adjust:100%}body{margin:0}a{background-color:transparent}code{font-family:monospace,monospace;font-size:1em}[hidden]{display:none}html{font-family:system-ui,-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica Neue,Arial,Noto Sans,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji;line-height:1.5}*,:after,:before{box-sizing:border-box;border:0 solid #e2e8f0}a{color:inherit;text-decoration:inherit}code{font-family:Menlo,Monaco,Consolas,Liberation Mono,Courier New,monospace}svg,video{display:block;vertical-align:middle}video{max-width:100%;height:auto}.bg-white{--bg-opacity:1;background-color:#fff;background-color:rgba(255,255,255,var(--bg-opacity))}.bg-gray-100{--bg-opacity:1;background-color:#f7fafc;background-color:rgba(247,250,252,var(--bg-opacity))}.border-gray-200{--border-opacity:1;border-color:#edf2f7;border-color:rgba(237,242,247,var(--border-opacity))}.border-gray-400{--border-opacity:1;border-color:#cbd5e0;border-color:rgba(203,213,224,var(--border-opacity))}.border-t{border-top-width:1px}.border-r{border-right-width:1px}.flex{display:flex}.grid{display:grid}.hidden{display:none}.items-center{align-items:center}.justify-center{justify-content:center}.font-semibold{font-weight:600}.h-5{height:1.25rem}.h-8{height:2rem}.h-16{height:4rem}.text-sm{font-size:.875rem}.text-lg{font-size:1.125rem}.leading-7{line-height:1.75rem}.mx-auto{margin-left:auto;margin-right:auto}.ml-1{margin-left:.25rem}.mt-2{margin-top:.5rem}.mr-2{margin-right:.5rem}.ml-2{margin-left:.5rem}.m`

### Error - 11205 HTTP connection failure
**MESSAGE**
`HTTP Connection Failure - Read timed out`

**Request URL**
`https://centralindianana.org/yap/meeting-search.php`

**Request Parameters**
`Called | "+13178755459"
-- | --
ToState | "IN"
CallerCountry | "US"
Direction | "inbound"
CallerState | "IN"
ToZip | "46032"
CallSid | "CAdf5a441bae4805c3434aa9b8a88150f0"
To | "+13178755459"
CallerZip | ""
ToCountry | "US"
ApiVersion | "2010-04-01"
CalledZip | "46032"
CallStatus | "in-progress"
CalledCity | "INDIANAPOLIS"
From | "+14632241294"
AccountSid | "AC59a0c75be25ea9a0cf7fa6e944ea5c54"
CalledCountry | "US"
CallerCity | ""
Caller | "+14632241294"
FromCountry | "US"
ToCity | "INDIANAPOLIS"
FromCity | ""
CalledState | "IN"
FromZip | ""
FromState | "IN"`

**Request Message Text**
`msg | "HTTP Connection Failure - Read timed out"
-- | --
Msg | "HTTP Connection Failure - Read timed out"
sourceComponent | "13700"
ErrorCode | "11205"
url | "meeting-search.php?Latitude=39.7606013&Longitude=-86.5263879"
LogLevel | "ERROR"`

No Response headers or body

### Error - 11205 HTTP connection failure
**MESSAGE**
`Request to https://centralindianana.org/yap/endpoints/status.php timed out`

No Request URL or Parameters

**Request Message Text**
`Msg | "Request to https://centralindianana.org/yap/endpoints/status.php timed out"
-- | --
statusCallback | "https://centralindianana.org/yap/endpoints/status.php"
ErrorCode | "11205"
LogLevel | "WARNING"
url | "https://centralindianana.org/yap/endpoints/status.php"`

No Response headers or body

**Comment by dgershman** [comment] 2021-12-06 22:49
@klgrimley your status callback should be https://centralindianana.org/yap/status.php, however it looks like there is a server error.  You would need to check the laravel.log file in app/storage/logs directory on your Yap install for the exact error.  I suspect this is the reason why reporting in not working for you.   That URL might have worked in previous versions of Yap, however it was never documented to use `/endpoints`, which was rewritten through the .htaccess file in versions prior to 4.x.

**Comment by klgrimley** [comment] 2021-12-06 22:52
I've update the status callback to  https://centralindianana.org/yap/status.php Thanks.

**Comment by dgershman** [comment] 2021-12-06 22:53
Try to dial in and see if you get call records.  I believe that 500 error
is me hitting the endpoint without the req'd params, and not great error
handling on that page.

**Comment by klgrimley** [comment] 2021-12-06 22:54
Would uploading the error log help at all?

**Comment by dgershman** [comment] 2021-12-06 22:55
Not at this time, I'm curious to see if you get a good call record in
reports now.

**Comment by dgershman** [comment] 2021-12-06 22:56
> 

@alanb2718 there seems to be some detail missing here in terms of what the actual failed HTTP call was.

**Comment by klgrimley** [comment] 2021-12-06 22:57
@dgershman Yep, called and it's logging in YAP admin.

**Comment by dgershman** [comment] 2021-12-06 22:57
Ok that was it then.

**Comment by dgershman** [comment] 2021-12-06 22:59
@klgrimley I am unable to repro the connection timeout errors.  They could be transient errors from your server.

**Comment by dgershman** [comment] 2021-12-06 23:00
the other error i see here is related to https://github.com/bmlt-enabled/yap/issues/570

**Comment by klgrimley** [comment] 2021-12-06 23:00
@dgershman The same as what Alan is seeing? That was my initial thought. Just hadn't seen them prior to upgrading to 4.0.0

**Comment by dgershman** [comment] 2021-12-06 23:01
That may be the case, but given the information here, I don't know how to reproduce the error.

**Comment by klgrimley** [comment] 2021-12-06 23:02
No worries. If it becomes more prevalent on my end I'll respond here.

**Comment by alanb2718** [comment] 2021-12-07 01:06
@dgershman regarding the missing detail, here is as much as I can capture from Twilio.  Does this have what you need?  If not, how about if I make you a login on our Twilio account?

[call-record.pdf](https://github.com/bmlt-enabled/yap/files/7664645/call-record.pdf)

**Comment by dgershman** [comment] 2021-12-07 01:09
From this information it’s not clear what is going on.  I would rather not log into your Twilio account.

**Comment by dgershman** [comment] 2021-12-07 01:16
I am going to look at some general Laravel performance changes for 4.0.2.

**Comment by spiritualtheory** [comment] 2021-12-08 16:40
Starting to see the HTTP Connection errors on NNY's Yap
Three in the last 24 hours, plus one 4 days ago

Prior to this we had this error 5 times across all of 2021, and about the same for 2020 - so with 3 happening in a day plus seeing a few others showing a sudden increase, thought this might be relevant

The 3 in the last 24 hours were:
Request to https://nny-na.org/yap/status.php timed out

HTTP Connection Failure - Read timed out
"https://nny-na.org/yap/input-method-result.php?SearchType=2"

HTTP Connection Failure - Read timed out
"https://nny-na.org/yap/index.php"

Still on version 3.9.9

**Comment by dgershman** [comment] 2021-12-18 16:08
Checking in on this, are you still seeing this occur.

**Comment by alanb2718** [comment] 2021-12-18 17:48
It hasn't been happening recently - the last error for Seattle Area was 12/05/2021.

**Comment by dgershman** [comment] 2021-12-18 22:51
That’s good to hear.

**Comment by dgershman** [comment] 2021-12-25 20:48
Since this was a transient issue related to the AWS outage I am going to close this out.  It seems unrelated to any specific version of Yap.  There are instructions on how to configure a fallback action in a secondary location https://github.com/bmlt-enabled/yap/issues/516#issuecomment-812288312.

**Closed** 2021-12-25 20:48 UTC
Labels: bug
