### ISSUE TITLE
Multiple voicemail notifications

### ISSUE THREAD

**Issue by pjaudiomv** [bmlt-enabled/yap#300] opened 2019-07-26 00:03 UTC
**Describe the bug**
When a volunteer calls an addict back while the addict is leaving voicemail, then the addict switches to new incoming call the volunteer gets multiple voicemail ntoification txts roughly every 20 secs for full duration of call.

**What version are you running?**
Latest

**Did this happen on prior versions to the one you are running?**
Not sure

**To Reproduce**
1. Call helpline as "caller"
2. Don't pickup as "volunteer"
3. "caller" gets sent to voicemail
4. "volunteer" calls "caller" back while leaving voicemail
5. "caller" then does not end call but switches to incoming call from "volunteer"
6. "volunteer" gets `You have a message from the service body helpline` text roughly every 20seconds for duration of call.

**Expected behavior**
Notification only gets sent once. this could be solved by either forcing ending of voicemail call or better solution to check see how many volunteers should be getting txts and only sending 1 per notification.

**Screenshots**

**Additional context**

**Comment by radius314** [comment] 2019-07-26 00:04
Ooh interesting bug.  Can you send me the logs from twilio?

**Comment by pjaudiomv** [comment] 2019-07-26 00:05
yea I was excited volunteer bothered to tell me about it, sure thing.

**Comment by radius314** [comment] 2019-08-18 13:16
I'm guessing your `call_timeout` is set to the default 20 seconds on the service body?

**Comment by pjaudiomv** [comment] 2019-08-18 13:26
Yes that's correct

**Comment by radius314** [comment] 2019-08-18 19:53
The repro steps are actually quite simpler.  If you are the "caller" and don't hang up after leaving a voicemail, you get an infinite loop of being asked to leave a voicemail.  The root cause of this issue is that after leaving a voicemail, the call is not ended.  The fix here is going to be to actually hang up the call after the voicemail-complete.php callback executes.

**Comment by radius314** [comment] 2019-08-18 20:12
available in master and will be in 3.4.0

**Comment by radius314** [comment] 2019-08-31 16:31
@pjaudiomv were you able validate this fix?

**Comment by pjaudiomv** [comment] 2019-08-31 23:28
i tested this and now the call is terminated after 20sec. so if you wanted to leave a voicemail passed 20sec your call would end and you would not be able to do so.

**Comment by radius314** [comment] 2019-08-31 23:31
Do you mean the voicemail stage is terminated after 20 seconds?

**Comment by pjaudiomv** [comment] 2019-08-31 23:31
thats correct

**Comment by radius314** [comment] 2019-08-31 23:33
Did you start talking, or was there dead air?  AFAIK, this may not be a regression.  The timeout has been set for 15 seconds possibly always (times out after silence).  

https://www.twilio.com/docs/voice/twiml/record#attributes-timeout

**Comment by radius314** [comment] 2019-08-31 23:34
ref: https://github.com/bmlt-enabled/yap/blob/master/endpoints/voicemail.php#L22

**Comment by pjaudiomv** [comment] 2019-08-31 23:37
oh cool I did not know that, yea there was silence. I just tried again and talked a bunch of gibberish for a minute then waited 15 secs and the call dropped. yea this feature works fine now then. Thanks

**Comment by radius314** [comment] 2019-08-31 23:37
cool

**Closed by radius314** 2019-08-31 23:37 UTC
Labels: bug
