### ISSUE TITLE
YAP Usage Summary Graphics don't match reporting for Area Service Bodies (Sub Regional)

### ISSUE THREAD

**Issue by brustar64** [bmlt-enabled/yap#586] opened 2022-04-06 07:06 UTC
**Describe the bug**
The useage summary report for Area service bodies stopped around the end of Dec/ beginning of January for most of our service bodies.  the "All" Regional summary shows correctly its just when you go down to the Area level it stops showing on the graph.

**What version are you running?**t
4.0.3 but also tried 4.04 as a test which didn't change the results.

**Did this happen on prior versions to the one you are running?**
I'm not sure.  It was not something we noticed.  One of our coordinators flagged this with us.

**To Reproduce**
1. Go to 'Reports'
2. Click on 'Select a Service Body' and select a Service body.
3. float your mouse over the last date in the usage summary graph to see the last reported date.  
4. Scroll down to the list of calls and see if the date's area aligned.

**Expected behavior**
We expect the same number of calls listed in the summary as occurred in the log.

**Screenshots**

Example Summary for Cairns
<img width="1154" alt="image" src="https://user-images.githubusercontent.com/29008815/161914713-913be191-983e-412f-92a9-e3c226e2dd13.png">

Does not match the call history 
<img width="741" alt="image" src="https://user-images.githubusercontent.com/29008815/161914873-ea1eca48-5752-4de2-9a41-57c58634d163.png">

**Additional context**
This issue is occurring for all service bodies but we may have a bigger issue because it looks like the Sydney Areas are not receiving any calls since January.  I tried a couple of calls and it went through to voicemail.

**Comment by dgershman** [comment] 2022-04-06 13:28
This is a duplicate of some issues reported on #530

**Comment by dgershman** [comment] 2022-05-08 18:06
You can try out [4.0.5-beta1]()https://github.com/bmlt-enabled/yap/releases/download/4.0.5-beta1/yap-4.0.5-beta1.zip which should fix this.

**Comment by brustar64** [comment] 2022-05-10 00:29
Thanks Danny
I'll update.
________________________________

**Comment by dgershman** [comment] 2022-05-28 14:54
Were you able to update?

**Comment by brustar64** [comment] 2022-05-29 04:01
Hi Danny,
Apologies for the late reply.  I've upgraded.  Should I be able to see results immediately or will will I need to wait for new calls to come in?

**Comment by dgershman** [comment] 2022-05-29 12:54
You should see results immediately.

**Comment by dgershman** [comment] 2022-06-03 20:32
What did you find?

**Comment by brustar64** [comment] 2022-06-04 06:02
It doesn't seem to make any difference whether I choose recursively or not.


  1.  I select Sydney Metro which is essentially a parent service body for  Sydney East, West, South and North.
     *   [cid:a86c6939-af06-4c90-b51c-979407e1134d]
  2.  Then I select recursively
     *   [cid:1b025264-353d-4ec1-98dc-4e23ba251309]

They are both the same.  I was expecting to Sydney metro to contain all the meetings from all the service bodies below it but it seems to have meetings that belong to it only and not to the service bodies below it.

Here is Sydney East, some of the calls and times match but some don't show at all under Sydney Metro.  I thought recursive selection would show all calls contained in all service bodies beneath it.

[cid:0b5bd0de-1827-46ac-964c-6cb30792eb52]

Sydney North
[cid:9a495e5f-ff1f-467e-aa17-fc722011b542]

Sydney South

[cid:e140d1cc-9813-4d21-9e0e-9762b9753f70]

I hope this explains it properly.
________________________________

**Comment by dgershman** [comment] 2022-06-04 11:44
Makes sense I’ll take a look at this use case.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by dgershman** [comment] 2022-07-30 01:09
Fixes Available in 4.1.0-beta2 if you want to test. 

https://github.com/bmlt-enabled/yap/releases/tag/4.1.0-beta2

**Comment by dgershman** [comment] 2022-08-06 20:57
fixes released in 4.1.0

**Closed by dgershman** 2022-08-06 20:57 UTC
Labels: bug
