### ISSUE TITLE
yap authentication problems with 4.3.1 for some users

### ISSUE THREAD

**Issue by alanb2718** [bmlt-enabled/yap#973] opened 2024-03-20 00:03 UTC
**Describe the bug**
Authentication is not working for a few users with 4.3.1 using BMLT authentication.  This is reproducible, but I don't know why a few users are affected and others not.

**What version are you running?**
4.3.1

**Did this happen on prior versions to the one you are running?**
No.  (I verified that the same user can log in with 4.2.11, or for the second error, save the edit.)

**To Reproduce**
1. Try to log in to the test server at https://test.wszf.org/yap/admin, user CentralValleyNorthArea.
2. See error "Not Authorized".

There is another error, which perhaps arises from the same underlying issue.  Steps to reproduce:
1. Log in to the test server https://test.wszf.org/yap/admin, user WesternStatesZonalForum.
2. Go to Volunteers for Washington / Northern Idaho Region.
3. Make a change (enabling or disabling a volunteer), and try to save.
4. Notice that the change does not get saved.

**Expected behavior**
Should be able to log in, or save the results of the edit.

**Additional context**
The user CentralValleyNorthArea **can** log in to the BMLT server at https://test.wszf.org/main_server/, and also the old version of yap at https://test.wszf.org/yap-4.2.11/admin.  Similarly, the user WesternStatesZonalForum can save change on the 4.2.11 version.

**Comment by dgershman** [comment] 2024-03-20 00:04
Yeah interestingly enough, @californiasteve reported a similar issue, but I couldn't reproduce it.

**Comment by dgershman** [comment] 2024-03-20 02:30
Do you see a javascript error when you try to save the volunteer?

**Comment by alanb2718** [comment] 2024-03-20 03:01
Yes - there is a warning when first selecting the "Volunteers" tab, then an error when I try to save.  Here is a screenshot.
![yap-error](https://github.com/bmlt-enabled/yap/assets/918773/6a674093-8b8d-4a97-801f-771dfdfdbf3b)

**Comment by dgershman** [comment] 2024-03-20 03:56
figured out this issue, it was double urlencoding.  fix coming soon

**Comment by dgershman** [comment] 2024-03-20 22:57
Can you try this out?  https://s3.amazonaws.com/archives.bmlt.app/yap/yap-394-39dbab72c2c7375c20916b469683715d649d08cb.zip

Also can you email your database to me so I can try to reproduce the javascript error?

**Comment by alanb2718** [comment] 2024-03-20 23:50
Yes, that works for the CentralValleyNorthArea login issue!  The problem with saving volunteers for Washington / Northern Idaho Region is still there.  I'll email you the database now.

**Comment by dgershman** [comment] 2024-03-20 23:53
That’s what I suspected.  Im’ going to close this and split that off into a new ticket.

From: Alan B ***@***.***>
Date: Wednesday, March 20, 2024 at 7:50 PM
To: bmlt-enabled/yap ***@***.***>
Cc: Danny Gershman ***@***.***>, Assign ***@***.***>
Subject: Re: [bmlt-enabled/yap] yap authentication problems with 4.3.1 for some users (Issue #973)

Yes, that works for the CentralValleyNorthArea login issue! The problem with saving volunteers for Washington / Northern Idaho Region is still there. I'll email you the database now.

**Closed** 2024-03-20 23:54 UTC
Labels: bug
