### ISSUE TITLE
Error running upgrade on clean new database...

### ISSUE THREAD

**Issue by gutterwall** [bmlt-enabled/yap#232] opened 2019-02-06 22:41 UTC
Fatal error: Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'timestamp' in /homepages/4/d330097172/htdocs/yap3/lib/Database.php:45 Stack trace: #0 /homepages/4/d330097172/htdocs/yap3/lib/Database.php(45): PDO->exec('CREATE TABLE `m...') #1 /homepages/4/d330097172/htdocs/yap3/endpoints/_includes/migrations.php(25): Database->exec('CREATE TABLE `m...') #2 /homepages/4/d330097172/htdocs/yap3/endpoints/_includes/functions.php(4): require_once('/homepages/4/d3...') #3 /homepages/4/d330097172/htdocs/yap3/admin/header.php(2): require_once('/homepages/4/d3...') #4 /homepages/4/d330097172/htdocs/yap3/admin/index.php(2): require_once('/homepages/4/d3...') #5 {main} thrown in /homepages/4/d330097172/htdocs/yap3/lib/Database.php on line 45

**Comment by radius314** [comment] 2019-02-06 22:59
what version of mysql you running?

**Comment by radius314** [comment] 2019-02-06 23:01
I'm assuming you are running beta4, correct?

**Comment by gutterwall** [comment] 2019-02-06 23:06
MySQL 5.5 yes beta from Sunday afternoon...

**Comment by radius314** [comment] 2019-02-07 01:11
I have been able to reproduce.

**Comment by radius314** [comment] 2019-02-07 01:20
@gutterwall you can test this fix with this build.  
https://archives.bmlt.app/yap/yap-757-2d00a0acad1e046b26cd621cad106137e6473d32.zip

**Comment by gutterwall** [comment] 2019-02-07 03:24
Yes that worked, as far as getting though the conversion
 I will test tomorrow ...

Thanks for your hard work!!! It is creating buzz and excitement for PI,
which hasn't happened in a long time!

**Comment by radius314** [comment] 2019-02-07 03:25
Great, I’m going to close this ticket out since it’s related to a beta.  Please open tickets for any other issues you find.

**Closed** 2019-02-07 03:25 UTC
Labels: trouble, v3
