### ISSUE TITLE
UI hangs when trying to retrieve volunteers

### ISSUE THREAD

**Issue by alanb2718** [bmlt-enabled/yap#809] opened 2023-06-16 21:04 UTC
An admin reports that trying to retrieve volunteers hangs for their area.  I am able to reproduce this behavior -- going to "Volunteers" then picking that service body gives a spinning disk that says "Retrieving Volunteers" and hangs there.

The admin turned on gender routing, and started picking genders for all the volunteers -- they reported being about halfway through.  So I suspect it is some problem connected with gender routing.  I have a copy of the db if needed.

This occurs only for the one area; retrieving the volunteers for other areas and regions is still OK.

This is yap v4.2.8 for Western States Zonal Forum.

**Comment by dgershman** [comment] 2023-06-16 21:08
Do you get any JavaScript errors?  Any http errors?

**Comment by alanb2718** [comment] 2023-06-16 21:22
Javascript says there is an error when I hit Volunteers - see this screenshot:
![yap-error](https://github.com/bmlt-enabled/yap/assets/918773/2f75f168-658f-4391-891a-2e68b8a9e24b)


The larval log has errors also about favicon:
```

[previous exception] [object] (ErrorException(code: 0): require(/home/customer/www/bmlt.wszf.org/public_html/yap//legacy/admin/favicon.ico/index.php): Failed to open stream: No such file or directory at /home/customer/www/bmlt.wszf.org/public_html/yap/storage/framework/views/bfcecae38f61fbfb06261581887f41c76a5cbcfe.php:3)
[stacktrace]
#0 /home/customer/www/bmlt.wszf.org/public_html/yap/storage/framework/views/bfcecae38f61fbfb06261581887f41c76a5cbcfe.php(3): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'require(/home/c...', '/home/customer/...', 3)
#1 /home/customer/www/bmlt.wszf.org/public_html/yap/storage/framework/views/bfcecae38f61fbfb06261581887f41c76a5cbcfe.php(3): require()
#2 /home/customer/www/bmlt.wszf.org/public_html/yap/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(107): require('/home/customer/...')
#3 /home/customer/www/bmlt.wszf.org/public_html/yap/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(108): Illuminate\\Filesystem\\Filesystem::Illuminate\\Filesystem\\{closure}()
#4 /home/customer/www/bmlt.wszf.org/public_html/yap/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(58): Illuminate\\Filesystem\\Filesystem->getRequire('/home/customer/...', Array)
#5 /home/customer/www/bmlt.wszf.org/public_html/yap/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(61): Illuminate\\View\\Engines\\PhpEngine->evaluatePath('/home/customer/...', Array)
#6 /home/customer/www/bmlt.wszf.org/public_html/yap/vendor/laravel/framework/src/Illuminate/View/View.php(139): Illuminate\\View\\Engines\\CompilerEngine->get('/home/customer/...', Array)
#7 /home/customer/www/bmlt.wszf.org/public_html/yap/vendor/laravel/framework/src/Illuminate/View/View.php(122): Illuminate\\View\\View->getContents()
#8 /home/customer/www/bmlt.wszf.org/public_html/yap/vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\\View\\View->renderContents()
#9 /home/customer/www/bmlt.wszf.org/public_html/yap/vendor/laravel/framework/src/Illuminate/Http/Response.php(69): Illuminate\\View\\View->render()
#10 /home/customer/www/bmlt.wszf.org/public_html/yap/vendor/laravel/framework/src/Illuminate/Http/Response.php(35): Illuminate\\Http\\Response->setContent(Object(Illuminate\\View\\View))
#11 /home/customer/www/bmlt.wszf.org/public_html/yap/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(55): Illuminate\\Http\\Response->__construct(Object(Illuminate\\View\\View), 200, Array)
#12 /home/customer/www/bmlt.wszf.org/public_html/yap/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(85): Illuminate\\Routing\\ResponseFactory->make(Object(Illuminate\\View\\View), 200, Array)
#13 /home/customer/www/bmlt.wszf.org/public_html/yap/app/Http/Controllers/LegacyController.php(28): Illuminate\\Routing\\ResponseFactory->view('legacy', Array)
#14 /home/customer/www/bmlt.wszf.org/public_html/yap/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Http\\Controllers\\LegacyController->index(Object(Illuminate\\Http\\Request), 'admin/favicon.i...')
#15 /home/customer/www/bmlt.wszf.org/public_html/yap/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('index', Array)
#16 /home/customer/www/bmlt.wszf.org/public_html/yap/vendor/laravel/framework/src/Illuminate/Routing/Route.php(262): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Http\\Controllers\\LegacyController), 'index')
#17 /home/customer/www/bmlt.wszf.org/public_html/yap/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()
#18 /home/customer/www/bmlt.wszf.org/public_html/yap/vendor/laravel/framework/src/Illuminate/Routing/Router.php(721): Illuminate\\Routing\\Route->run()
#19 /home/customer/www/bmlt.wszf.org/public_html/yap/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#20 /home/customer/www/bmlt.wszf.org/public_html/yap/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#21 /home/customer/www/bmlt.wszf.org/public_html/yap/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#22 /home/customer/www/bmlt.wszf.org/public_html/yap/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#23 /home/customer/www/bmlt.wszf.org/public_html/yap/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#24 /home/customer/www/bmlt.wszf.org/public_html/yap/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#25 /home/customer/www/bmlt.wszf.org/public_html/yap/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#26 /home/customer/www/bmlt.wszf.org/public_html/yap/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#27 /home/customer/www/bmlt.wszf.org/public_html/yap/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest(Object(Illuminate\\Http\\Request), Object(Illuminate\\Session\\Store), Object(Closure))
#28 /home/customer/www/bmlt.wszf.org/public_html/yap/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#29 /home/customer/www/bmlt.wszf.org/public_html/yap/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#30 /home/customer/www/bmlt.wszf.org/public_html/yap/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#31 /home/customer/www/bmlt.wszf.org/public_html/yap/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#32 /home/customer/www/bmlt.wszf.org/public_html/yap/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#33 /home/customer/www/bmlt.wszf.org/public_html/yap/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#34 /home/customer/www/bmlt.wszf.org/public_html/yap/vendor/laravel/framework/src/Illuminate/Routing/Router.php(723): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#35 /home/customer/www/bmlt.wszf.org/public_html/yap/vendor/laravel/framework/src/Illuminate/Routing/Router.php(698): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#36 /home/customer/www/bmlt.wszf.org/public_html/yap/vendor/laravel/framework/src/Illuminate/Routing/Router.php(662): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#37 /home/customer/www/bmlt.wszf.org/public_html/yap/vendor/laravel/framework/src/Illuminate/Routing/Router.php(651): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#38 /home/customer/www/bmlt.wszf.org/public_html/yap/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(167): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#39 /home/customer/www/bmlt.wszf.org/public_html/yap/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#40 /home/customer/www/bmlt.wszf.org/public_html/yap/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#41 /home/customer/www/bmlt.wszf.org/public_html/yap/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#42 /home/customer/www/bmlt.wszf.org/public_html/yap/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#43 /home/customer/www/bmlt.wszf.org/public_html/yap/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#44 /home/customer/www/bmlt.wszf.org/public_html/yap/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#45 /home/customer/www/bmlt.wszf.org/public_html/yap/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#46 /home/customer/www/bmlt.wszf.org/public_html/yap/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#47 /home/customer/www/bmlt.wszf.org/public_html/yap/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#48 /home/customer/www/bmlt.wszf.org/public_html/yap/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#49 /home/customer/www/bmlt.wszf.org/public_html/yap/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#50 /home/customer/www/bmlt.wszf.org/public_html/yap/vendor/fruitcake/laravel-cors/src/HandleCors.php(38): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#51 /home/customer/www/bmlt.wszf.org/public_html/yap/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#52 /home/customer/www/bmlt.wszf.org/public_html/yap/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#53 /home/customer/www/bmlt.wszf.org/public_html/yap/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#54 /home/customer/www/bmlt.wszf.org/public_html/yap/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#55 /home/customer/www/bmlt.wszf.org/public_html/yap/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#56 /home/customer/www/bmlt.wszf.org/public_html/yap/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#57 /home/customer/www/bmlt.wszf.org/public_html/yap/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#58 {main}
"} 

```

**Comment by dgershman** [comment] 2023-06-16 21:24
Are there any http requests that failed in the network tab?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by alanb2718** [comment] 2023-06-16 21:26
Yes, it is having trouble with favicon.ico -- also this gives a server error:

https://bmlt.wszf.org/yap/admin/favicon.ico

**Comment by dgershman** [comment] 2023-06-16 21:50
I was more curious about other requests.  A favicon not loading wouldn’t cause that issue.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by alanb2718** [comment] 2023-06-16 21:53
All the other requests are being served without error, it says.

**Comment by dgershman** [comment] 2023-06-16 22:16
Ok email me the database and config.  I’ll try to look at it this weekend.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by alanb2718** [comment] 2023-06-16 22:40
Thanks - will do.

**Comment by dgershman** [comment] 2023-06-18 21:19
Which area is this?

**Comment by dgershman** [comment] 2023-06-18 21:22
Guessing it's the Central Coast Area.

**Comment by dgershman** [comment] 2023-06-18 21:37
If this is the area, then the issue appears to be that the data was truncated somehow.  My thought is that it might be related to some issue with your data collation.  The size of that field `data` in the `config` table should be able to hold 64k of data.  If it is encoding it as unicode then it would hit that limit.  I couldn't reproduce the issue on my end.  Once way to test this theory out is for us to change the field type to a `MEDIUMTEXT` field.  We'd also have to update the column so that it fixes the data corruption issue.  I'll email you the query to run on your database (note that there will be some data loss here on whatever the last volunteers were).

**Comment by alanb2718** [comment] 2023-06-18 21:39
OK.  Yes, it was Central Coast Area.

**Comment by dgershman** [comment] 2023-06-19 00:32
It turns out this was related to the database field size and a large amount of volunteers.  Will be fixing this in 4.2.9.

**Comment by dgershman** [comment] 2023-06-19 00:44
yap 4.2.9 was released with this fix.

**Closed by dgershman** 2023-06-19 00:44 UTC
Labels: bug
