### ISSUE TITLE
Yap created users are not restricted to their own service bodies and can manage other users

### ISSUE THREAD

**Issue by brustar64** [bmlt-enabled/yap#486] opened 2020-10-22 10:35 UTC
**Describe the bug**
All users created in YAP have full rights to all other service bodies and user privileges. 

**What version are you running?**
3.9.5

**Did this happen on prior versions to the one you are running?**

**To Reproduce**
1. log in with original admin account
2. Go to users
3. Select any other user confirm that "manage users" is not selected. Confirm that only relevant service bodies are selected.
4. Save user
5. Log in with the "other" user account that you just checked.
6. Go to service bodies (all service bodies are visible and editable)
7. Go to reports all reports for all service bodies are visible
8. Same deal exists for settings, Volunteers, Groups and Users

**Expected behavior**
users should not be able to manage other users unless "Manage Users" is selected
users should only be able to see the service bodies selected in their user account.

**Screenshots**
Example account that can see and do everything across the entire platform...
![image](https://user-images.githubusercontent.com/29008815/96860242-de7faa00-14a5-11eb-98b5-959d720b1b59.png)

**Additional context**
Users created in BMLT can only see the the service body rights assigned to them in BMLT

**Comment by radius314** [comment] 2020-10-24 15:25
Unable to reproduce

**Comment by brustar64** [comment] 2020-10-24 21:38
Would you like me to create a test user for you?

**Comment by radius314** [comment] 2020-10-24 21:39
I don't think that will be helpful to me, please email a database export to the help email.

**Comment by radius314** [comment] 2020-10-25 02:34
Unable to reproduce.  My suggestion would be to upgrade to 3.9.7 and see if this issue still persists.

**Comment by brustar64** [comment] 2020-10-25 08:50
Upgraded to 3.9.7 - issue still exists

**Comment by brustar64** [comment] 2020-10-25 08:56
Created a new user.  Irrespective of whether or not I choose "manage users", the "Admin" box is checked.
![Screen Shot 2020-10-25 at 6 53 22 pm](https://user-images.githubusercontent.com/29008815/97102746-c1401b00-16f3-11eb-8d91-8a503f26e8fb.png)
Tried editing the user by checking "manage users" to see if I could toggle it however once selected unable to de-select "manage users".

**Comment by radius314** [comment] 2020-10-25 13:02
You should be able to deselect by using one either the Control, Shift, or Command key (I forget which one) and clicking the option again. 

—Danny

On Oct 25, 2020, at 4:57 AM, brustar64 <notifications@github.com> wrote:

﻿
Created a new user. Irrespective of whether or not I choose "manage users", the "Admin" box is checked.

Tried editing the user by checking "manage users" to see if I could toggle it however once selected unable to de-select "manage users".

**Comment by radius314** [comment] 2020-10-25 17:15
I'm not sure how you were able to set those users as admins.

**Comment by brustar64** [comment] 2020-11-20 05:55
I didn't get any choice - any user created from a "Yap" user as opposed to a BMLT user gets full rights to everything.

**Comment by radius314** [comment] 2020-11-21 14:54
I haven't been able to reproduce this issue at all.  Are you getting the same behavior regardless of what browser you use?

**Comment by brustar64** [comment] 2020-11-21 21:26
I've only done this using Chrome.
I'll try a different browser.
________________________________

**Comment by brustar64** [comment] 2020-11-21 21:34
I just tried it in Edge
Created a new user (testyapgoldcoast) from an admin user account.
Selected only the Gold Coast service body and did not select the option for manage users.
however the "Admin" checkbox is still checked irrespective and the user is basically a super user within yap with access to all service bodies and all users.
![image](https://user-images.githubusercontent.com/29008815/99888045-2ce6bb00-2c95-11eb-971a-91acf13d72e4.png)

**Comment by radius314** [comment] 2020-11-22 03:33
I understand the issue, I just can't reproduce it.

**Comment by radius314** [comment] 2020-11-22 19:04
There is no way in the codebase for an admin to be created, it's literally impossible.  

The migration forces the default to be `0` on the bit field `is_admin` https://github.com/bmlt-enabled/yap/blob/48f612e60b6045155ae576c71d0c12e699560623/migrations/6.sql#L7

Also, the one place in code where an INSERT happens the default is 0 with no way to change it.

https://github.com/bmlt-enabled/yap/blob/73768634acb97c5fb07160a24e5f54af03892362/endpoints/_includes/queries.php#L471

**Comment by radius314** [comment] 2020-11-23 04:31
I have a little bit of a better idea of what's going on.  I'm working on a potential fix for this, it might take me a few days to get it right.

**Comment by radius314** [comment] 2020-11-24 04:21
fix for this will in 3.9.9

**Closed** 2020-11-24 04:37 UTC
Labels: question

**Comment by brustar64** [comment] 2020-11-24 21:46
When you created the first user in BMLT you did it through the back end somehow.
Could it be something to do with the way this user was created in this unique instance?
________________________________

**Comment by radius314** [comment] 2020-11-26 02:12
I'm not sure what you are saying here.  The issue has been fixed, upgrade to 3.9.9.
