### ISSUE TITLE
Service Bodies Configure Window Closing When + is Selected

### ISSUE THREAD

**Issue by californiasteve** [bmlt-enabled/yap#234] opened 2019-02-13 22:51 UTC
**Describe the bug**
When in the Service Bodies tab after selecting the configure tab + the modal closes.

**What version are you running?**
3.0.0-beta4

**Did this happen on prior versions to the one you are running?**

Link to [video](https://bmltyap.org/video/recording2.mp4)

**Comment by radius314** [comment] 2019-02-15 17:28
Could not reproduce.

**Comment by californiasteve** [comment] 2019-02-15 17:57
Here's what I'm seeing in my debugger, Firefox 65.0.1 (64-bit), Windows 7
ReferenceError: event is not defined[Learn More] yap.js:435:5

    addServiceBodyButtonClick https://bmltyap.org/arscna_3.0/admin/js/yap.js:435 onclick https://bmltyap.org/arscna_3.0/admin/service_bodies.php?blocklist=:1 

Source map error: request failed with status 404
Resource URL: https://bmltyap.org/arscna_3.0/admin/js/bootstrap-4.1.0.min.js
Source Map URL: bootstrap.min.js.map[Learn More]
Source map error: request failed with status 404
Resource URL: https://bmltyap.org/arscna_3.0/admin/js/popper.min.js
Source Map URL: popper.min.js.map[Learn More]

**Comment by radius314** [comment] 2019-03-04 03:06
Able to repro (Firefox only issue).

**Comment by radius314** [comment] 2019-03-04 03:19
will be released in yap 3 beta 5

**Comment by radius314** [comment] 2019-03-09 21:05
@californiasteve were you able to see if this was fixed?

**Comment by californiasteve** [comment] 2019-03-09 22:12
Yes, works as expected

**Closed** 2019-03-09 22:18 UTC
Labels: bug, v3
