### ISSUE TITLE
Reporting Issues

### ISSUE THREAD

**Issue by EzraKuhr** [bmlt-enabled/yap#530] opened 2021-08-13 03:26 UTC
1. When I go to 'all' (with and without "Select Recursively" enabled) I see data points in the graph for only Meetings and JFT
2a. When I select Florida Region (with/without "Select Recursively"), the graph is HYPER focused (x axis ticks are 1/2000th of a second) on Jan 16, 2021 (I think that was the first day I did some testing at the Regional level, though I think there may have been more since.
2b. When "Select Recursively" is off, the geographical map is hyper focused on the one data point, but the table is empty (even though there were 3 volunteer calls that day.
2c. When "Select Recursively" is on, the map and table populate with many many data points as expected. but not the plot graph which just shows the one.
3. When I drill into an area, the volunteers data points are the only one that show in the plot graph and geo map. I have no data points for meetings or JFT.
4. Days with zero data points dont seem to be accounted for, so looks like the baseline is y=1, not y=0. (Not sure if I explained this well, but basically the graph never hits zero when it should. The absence of data is just as important as its presence)

![image](https://user-images.githubusercontent.com/20930402/129300736-67d961b2-09f9-4352-b635-b3212d025536.png)
![image](https://user-images.githubusercontent.com/20930402/129300749-9e3997a5-26b6-4aa7-ac4a-50331a337cfb.png)
![image](https://user-images.githubusercontent.com/20930402/129300761-6ff13b64-ee7f-49fe-8e54-66bb095c3d3e.png)
![image](https://user-images.githubusercontent.com/20930402/129300770-a8718989-2032-4390-8520-e31b82f323ec.png)

**Comment by pjaudiomv** [comment] 2021-08-14 14:50
possibly related to https://github.com/bmlt-enabled/yap/issues/511

**Comment by dgershman** [comment] 2021-08-20 14:15
There was a bug related to recursively plot metrics.  That will be delivered in Yap 4.0.0-beta6.  I've not had a chance to parse through the rest of this yet.

**Comment by dgershman** [comment] 2021-09-03 02:54
@EzraKuhr can you validate if this issue is fixed on beta6?

**Comment by dgershman** [comment] 2021-10-09 19:37
@EzraKuhr can you validate if this issue is fixed on beta7?

**Comment by dgershman** [comment] 2021-12-25 20:49
Closing this out.  Please verify when you can.

**Comment by EzraKuhr** [comment] 2022-03-06 18:42
@dgershman Sorry for not paying attention to this. Please reopen this ticket. Looks like items 2 and 3 in OP are still unresolved on Yap 4.0.4. We have multiple areas requesting the reporting indicated in item 2. Reposting here:

2. When I drill into an area, the volunteers data points are the only one that show in the plot graph and geo map. I have no data points for meetings or JFT.
3. Days with zero data points dont seem to be accounted for, so looks like the baseline is y=1, not y=0. (Not sure if I explained this well, but basically the graph never hits zero when it should. The absence of data is just as important as its presence)
4. New related issue: I called the helpline pictured today (3/6/22), and I see it in the call log, but not in the graph. The most recent point in the graph was the last helpline call on 2/26/22

Thank you
![image](https://user-images.githubusercontent.com/20930402/156937180-44b211af-1146-42e0-813d-025497c4e6bb.png)
![image](https://user-images.githubusercontent.com/20930402/156937247-baf0ef24-bbfb-4825-b9b6-b061d353f8fe.png)
<img width="860" alt="image" src="https://user-images.githubusercontent.com/20930402/156937297-1df5a44e-f462-4cbf-a277-30b7ab1ec096.png">

**Comment by dgershman** [comment] 2022-03-16 00:29
@EzraKuhr first point, zero metrics, is addressed here https://github.com/bmlt-enabled/yap/pull/583

**Comment by EzraKuhr** [comment] 2022-03-16 00:30
Thank you Danny! Saw the snippets, and it seems to be exactly what we're looking for.

**Comment by dgershman** [comment] 2022-03-16 00:33
Regarding [item 2](https://github.com/bmlt-enabled/yap/issues/530#issuecomment-1060016799), unless you have a phone number tied to an area and it's called, there will be no meeting lookup or JFT metrics.  

There is no logical way, that I can think of to associate these lookups to an ASC, as they aren't tied to one.  

If you have an example of a phone call made to an ASC-specific number and a meeting search or JFT was done, I can look into it specifically.

Below is an example of an ASC number that does exactly what I described above:

<img width="1158" alt="image" src="https://user-images.githubusercontent.com/1850811/158494131-2c9a5701-48d3-4986-be24-927edc09115c.png">

**Comment by EzraKuhr** [comment] 2022-03-16 00:46
All areas in Florida and South Florida have their own number and the webhooks point an area's phone number to the area's service body in yap. We very much have a need for this. Have to collaborate to provide any information or access you need to assist with this.

**Comment by dgershman** [comment] 2022-03-16 00:47
The feature should work, to provide this level of metrics for ASCs.  I am noticing that there is a bug with metrics, but I haven't tracked it down yet.

**Comment by EzraKuhr** [comment] 2022-03-16 00:54
*happy to collaborate 

Ok, thank you for your hard work.

**Comment by dgershman** [comment] 2022-03-19 18:33
Ok I think I have tracked down the issue with the metrics.  Looks like a query issue that needs to be fixed, not a data loss issue.

**Comment by dgershman** [comment] 2022-04-04 01:14
There are some fixes headed for yap 4.0.5 that should fix a bug with how PHP was scoping one of the variables that are used for reporting.  The release will also deal with the bad data.

**Comment by dgershman** [comment] 2022-04-04 01:14
#585

**Comment by dgershman** [comment] 2022-04-04 01:16
Here is what the chart looks like for Space Coast Area.  The last little spike is test data.

<img width="1139" alt="image" src="https://user-images.githubusercontent.com/1850811/161458721-2269b2a3-f4cb-42a6-a63b-b7e480cbde20.png">

**Comment by EzraKuhr** [comment] 2022-04-04 01:18
It still looks like the meeting lookups and JFT metrics are missing.

**Comment by dgershman** [comment] 2022-04-04 01:43
I'm not sure if you saw this comment from a few days ago https://github.com/bmlt-enabled/yap/issues/530#issuecomment-1068605260.  I hope that clarifies things.  The issue is that your phone numbers for ASC are set with override_service_body_config_id versus override_service_body_id.  At this time of a call without this being set there is no way to know what the service body is.

**Comment by EzraKuhr** [comment] 2022-04-04 01:46
I did not see that. Are there any other factors to know before switching to that override instead?

@MCzelusniak

**Comment by dgershman** [comment] 2022-04-04 01:47
It will basically eliminate location lookups for finding volunteers.  You can Provision a test number and set up webhooks to test it out.

**Comment by EzraKuhr** [comment] 2022-04-04 01:49
Got it. Thank you Danny! I alerted Michelle to my mistake. We will work on testing this and verifying that.

**Comment by dgershman** [comment] 2022-05-08 18:07
You can try out [4.0.5-beta1](https://github.com/bmlt-enabled/yap/issues/586)https://github.com/bmlt-enabled/yap/releases/download/4.0.5-beta1/yap-4.0.5-beta1.zip which should fix this.

**Comment by dgershman** [comment] 2022-07-30 01:10
Fixes Available in 4.1.0-beta2 if you want to test. 

https://github.com/bmlt-enabled/yap/releases/tag/4.1.0-beta2

**Comment by dgershman** [comment] 2022-08-06 20:59
fixes released in 4.1.0

**Closed by dgershman** 2022-08-06 20:59 UTC
Labels: bug, enhancement, question
