### ISSUE TITLE
Reporting Options

### ISSUE THREAD

**Issue by gutterwall** [bmlt-enabled/yap#110] opened 2018-07-23 01:55 UTC
It would be really helpful to have simplified reporting in YAP, so  we could pull reports per month of how many people called in, how many went to automated help, JFT, or tried to get a volunteer, and the number of those that were successful, and how long they talked.

Also, how many minutes total a month, and the ability to compare months or something in nice line charts suitable for use with the usual web analytics as part of our usual PR reporting.

I ask the world, but simple stats should be trivial to record, right?

**Comment by radius314** [comment] 2018-07-23 02:05
There is a ticket to add some call metrics for each service body.  Beyond that Twilio has all the bells and whistles pull reports, and I wouldn’t try to replicate that.

**Comment by radius314** [comment] 2018-07-23 19:04
This is related to #105

**Comment by gutterwall** [comment] 2018-07-24 19:49
Actually I see no where in Twilio to pull reports.  There is a overview csv you can download, and a api if you pay for insights.  I don't see a way to know if a user went to talk to a volunteer, or heard the jft, or got meeting information from the overview data.  Just minutes used and if an outbound call or calls were done during the call (to volunteers) but that is not a good report.  It would be cool to see per month how many attempts to volunteers/success and meeting and jft lookups were done so we could see usage by type.  The only way I can figure that out is to click on each call and go to details to see manually what action they took.  It would take a couple hours to categorize the call by type...

Just seems like a no brainer to be needed.  Since we aren't using their workflow engine, you dont get the normal call center reports they have canned.

**Comment by radius314** [comment] 2018-07-24 19:49
Go to programmable voice in the twilio menu.  All the reports are there.

**Comment by radius314** [comment] 2018-07-24 19:51
If there are more people interested in this, I'll consider building it in.

**Comment by radius314** [comment] 2018-07-25 03:07
looks like i'm going to have add a datastore into Yap to make this happen.  i need to hold off on this for a bit.  but other features on the roadmap are going to require this.

**Comment by radius314** [comment] 2018-12-06 02:31
Basic actions metrics are in `master`, slated for yap 3.x.

<img width="1382" alt="yap_admin" src="https://user-images.githubusercontent.com/1850811/49557264-15aa3980-f8d5-11e8-8726-b89ea5f8a641.png">

**Comment by radius314** [comment] 2018-12-25 23:18
Will be released in v3, in master now.  Lot's of room for improvement, but doing the bare minimum right now.

**Comment by gutterwall** [comment] 2018-12-25 23:35
Thanks! I will stand it up in test!

**Comment by gutterwall** [comment] 2018-12-27 03:54
I installed the yap 3.0 beta, and I set up the mysql database, and added it
to the working config from 2.* per instructions.  I got the following error
when logging into the admin console.

Fatal error: Uncaught Error: Class 'Twilio\Http\CurlClient' not found in
/homepages/4/d330097172/htdocs/yap3/vendor/twilio/sdk/Twilio/Rest/Client.php:166
Stack trace: #0
/homepages/4/d330097172/htdocs/yap3/endpoints/twilio-client.php(7):
Twilio\Rest\Client->__construct('ACa233020a3c857...', 'b57166706b661be...')
#1 /homepages/4/d330097172/htdocs/yap3/endpoints/functions.php(272):
require_once('/homepages/4/d3...') #2
/homepages/4/d330097172/htdocs/yap3/admin/home.php(3):
UpgradeAdvisor::getStatus() #3 {main} thrown in
/homepages/4/d330097172/htdocs/yap3/vendor/twilio/sdk/Twilio/Rest/Client.php on
line 166

I ran the upgrade advisor php but it just is blank with no errors.

I thought you should know.

**Comment by radius314** [comment] 2018-12-27 03:55
Where did you find the installation files?

**Comment by gutterwall** [comment] 2018-12-27 03:57
I downloaded the release of 3.0 beta zip and unzipped and uploaded to a new
folder.

Then copied my config.php and added the four new mysql values.

**Comment by radius314** [comment] 2018-12-27 03:57
What url?

**Comment by gutterwall** [comment] 2018-12-27 04:05
https://metrorichna.org/yap3/

**Comment by pjaudiomv** [comment] 2018-12-27 04:11
I think he means what url did you get the installation from

**Comment by pjaudiomv** [comment] 2018-12-27 04:11
do you have  a vendor folder and a .htaccess file in you yap3 folder

**Comment by gutterwall** [comment] 2018-12-27 04:13
yes I have those in the folder.

It's the zip file in releases for 3.0.0.1 beta or whatever, from your
github under releases...

Did I do it wrong?

**Comment by pjaudiomv** [comment] 2018-12-27 04:16
no that should be right, at first glance it seems like its not obeying the htaccess rules.

**Comment by radius314** [comment] 2018-12-27 04:17
According to the error the vendor folder might be missing.

You should be using this zip file.

https://github.com/bmlt-enabled/yap/releases/download/3.0.0-beta1/yap-3.0.0-beta1.zip

**Comment by radius314** [comment] 2018-12-27 04:18
Are you running Apache webserver ?

**Comment by radius314** [comment] 2018-12-28 02:48
Confirmed that you are running Apache.  As @pjaudiomv sugggested it looks like htaccess rules aren't being respected.  Specifically the Apache `mod_rewrite` module is most likely not loaded.

```
21:45:41 › curl --head https://metrorichna.org/yap3/
HTTP/2 404
content-type: text/html
date: Fri, 28 Dec 2018 02:45:45 GMT
server: Apache
```

**Comment by gutterwall** [comment] 2018-12-28 02:55
So how do I fix it?  I barely understand what you are saying, as I don't
use Apache much in actual.  More IIS experience at work...

**Comment by radius314** [comment] 2018-12-28 02:55
Do you want to set up a live session to poke around?

**Comment by gutterwall** [comment] 2018-12-28 03:09
I am retiring for the night.  How about tomorrow, when is a good time?

**Comment by radius314** [comment] 2018-12-28 03:10
Not sure I will be available.

**Comment by radius314** [comment] 2018-12-28 03:10
Who is your hosting provider?

**Comment by gutterwall** [comment] 2018-12-28 17:36
1and1, I checked and mod_rewrite rules are in the other htaccess files for
wordpress to work.  I tried running the sql in the migrations folder
directly against the table I had defined, and I get an error on the
timestamp creation in the second sql query.  I deleted all tables so it
would be clean again (I did get the first table created with the first
query).  I looked at the htaccess that came in your zip and it looks
similar to the one's in my 1&1 click and build wordpress instances.

Is it because I am using the Yap 2.0 configured BMLT database as well?  I
figured first you run the sql queries to create the new tables before
scanning the old BMLT database.  The Yap3.0 does display the current
volunteers and schedules.

THanks for all your help.  I am guessing it's because its and existing
system?

Or is there an easy fix?

I got a phpinfo at http://metrorichna.org/test.php if you wanna see that...

**Comment by radius314** [comment] 2018-12-28 17:40
You shouldn’t have to manually run the migrations, if all is working
correctly they would get applied naturally when running the upgrade advisor.

You should be using a clean database for Yap and not commingle it with the
root server database.

What version of MySQL are you running?

None of this explains why the Htaccess file seems to be ignored.

Danny

**Comment by gutterwall** [comment] 2018-12-28 17:44
mysql 5.5

It's not co-mingling the data, I did set up a new database per instructions.

I just noticed that you store the volunteers and stuff in the BMLT
database, right?

**Comment by radius314** [comment] 2018-12-28 17:46
Volunteers and configuration are stored in the BMLT database.

I think sorting out the Htaccess issue is something a little more
concerning right now. Bypassing the normal upgrade function isnt going to
get you far.

**Comment by radius314** [comment] 2019-03-11 03:19
Have you found anything?  Have you tried the latest beta?

**Closed** 2019-03-11 03:31 UTC
Labels: enhancement, v3

**Comment by gutterwall** [comment] 2019-03-11 09:40
I am still getting the same error with latest version...

**Comment by radius314** [comment] 2019-03-11 11:08
Are you downloading a zip file from the master branch?  Are you doing a git
clone?  Or are you using the release zip?

**Comment by radius314** [comment] 2019-03-11 13:32
Would like to figure out what’s going on here before we release Yap3.  Can
we set up a time where I can see what’s going on?

**Comment by gutterwall** [comment] 2019-03-11 16:31
I tried the lastest master, the 3x branch, etc

Maybe it's old data from Yap 1.x?  I don't know, do you want creds to test
it yourself?

**Comment by radius314** [comment] 2019-03-11 16:32
yeah sure, that would be great if you are willing.

**Comment by californiasteve** [comment] 2019-03-11 16:47
I get this in my reports view Danny. I have multiple numbers with multiple service bodies going to one account.
![image](https://user-images.githubusercontent.com/31661648/54141311-6a3ce380-43f3-11e9-9547-8d875f202f23.png)

**Comment by radius314** [comment] 2019-03-11 16:48
The report is aggregated across the entire instance.  For meeting list lookups and just for today playbacks there is no way to know the service body.   

If you'd like to see counts of helpline calls please file an enhancement ticket.

**Comment by californiasteve** [comment] 2019-03-11 16:49
Got it, thanks.
