### ISSUE TITLE
Request meetings for specific days of the week

### ISSUE THREAD

**Issue by EzraKuhr** [bmlt-enabled/yap#542] opened 2021-09-06 12:36 UTC
(Probably more like a Yap 4.1 thing...)
It would be very helpful to anyone trying to plan meetings in advance to be able to text a yap phoneline with a location and optional day (or key word "tomorrow") (no day specified would default to today) to get meeting info in advance.

**Comment by dgershman** [comment] 2021-09-06 21:57
Dupe of #174

**Closed** 2021-09-06 21:57 UTC
